-- generated by LazyWorkspacesBootstrap
-- workspace root (set by LazyWorkspacesBootstrap)
local workspace_root = "~/.config/nvim/"

vim.g.mapleader = " "
vim.g.maplocalleader = " "

-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--branch=stable",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

-- Bootstrap lazy-workspaces
local lwpath = vim.fn.stdpath("data") .. "/lazy/lazy-workspaces.nvim"
if not (vim.uv or vim.loop).fs_stat(lwpath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/ivankozlovcodes/lazy-workspaces.nvim.git",
		lwpath,
	})
end
vim.opt.rtp:prepend(lwpath)

local workspace_specs = {}
if (vim.uv or vim.loop).fs_stat(lwpath) then
	workspace_specs = require("lazy-workspaces").collect({
		workspaces = {
			{
				url = "file://" .. workspace_root,
				enable = { "common", "custom", "neovide" },
			},
		},
	})
end

require("lazy").setup({
	spec = vim.list_extend(workspace_specs, {
		{ "ivankozlovcodes/lazy-workspaces.nvim", opts = {} },
	}),
	rocks = { hererocks = true },
	change_detection = { notify = false },
})
